import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';
import type { Schema } from '../../amplify/data/resource';
import outputs from '../../amplify_outputs.json';

/**
 * `amplify_outputs.json` is generated by `npx ampx sandbox` (local) or
 * `ampx pipeline-deploy` (CI). It holds only public client configuration — the
 * same values that ship inside any built app bundle — so a placeholder version
 * is committed to keep the build green before the backend has ever been
 * deployed.
 *
 * When the placeholder is still in place there is no backend to talk to, so the
 * app says so plainly rather than failing with an opaque Amplify error.
 */
const isPlaceholder = (outputs as { _placeholder?: boolean })._placeholder === true;

export const isBackendConfigured = !isPlaceholder;

if (isBackendConfigured) {
  Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0]);
}

/**
 * Creating the client requires a configured API. Guard it so an unconfigured
 * build still loads far enough to render the explanation screen.
 */
function createClient() {
  try {
    return generateClient<Schema>();
  } catch {
    return null;
  }
}

export const client = createClient() as ReturnType<typeof generateClient<Schema>>;

export type OrganizationRecord = Schema['Organization']['type'];
export type EmployeeRecord = Schema['Employee']['type'];
export type AttendanceRecordType = Schema['AttendanceRecord']['type'];
